services:
  api-gateway:
    network_mode: "host"
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - redis

  auth-service:
    network_mode: "host"
    build:
      context: .
      dockerfile: src/auth/Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - redis

  data-service:
    network_mode: "host"
    build:
      context: .
      dockerfile: src/data/Dockerfile
    ports:
      - "4002:4002"
    depends_on:
      - redis

  redis:
    image: "redis"
    ports:
      - "6379:6379"
